/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author User
 */
public class Fhf_JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Fhf_JFrmPrincipal
     */
    public Fhf_JFrmPrincipal() {
        initComponents();
        setTitle("Cafeteria do Fernando");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnUsuarios = new javax.swing.JMenuItem();
        jMnClientes = new javax.swing.JMenuItem();
        jMnProdutos = new javax.swing.JMenuItem();
        jMnVendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro");

        jMnUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-usuário-24 (1).png"))); // NOI18N
        jMnUsuarios.setText("Usuários");
        jMnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMnUsuarios);

        jMnClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-grupo-de-usuários-24.png"))); // NOI18N
        jMnClientes.setText("Clientes");
        jMnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMnClientes);

        jMnProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-bebida-quente-24.png"))); // NOI18N
        jMnProdutos.setText("Produtos");
        jMnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jMnProdutos);

        jMnVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMnVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cafeteria-da-escola-24.png"))); // NOI18N
        jMnVendedor.setText("Vendedor");
        jMnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnVendedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMnVendedor);
        jMenu1.add(jSeparator1);

        jMnSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-sair-24.png"))); // NOI18N
        jMnSair.setText("Sair");
        jMnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMnSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimento");

        jMnVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        jMnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-bebida-quente-24.png"))); // NOI18N
        jMnVendas.setText("Vendas");
        jMnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnVendasActionPerformed(evt);
            }
        });
        jMenu2.add(jMnVendas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnUsuariosActionPerformed
        // TODO add your handling code here:
        Fhf_JDlgUsuarios jDlgUsuarios = new Fhf_JDlgUsuarios(null, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnUsuariosActionPerformed

    private void jMnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnClientesActionPerformed
        // TODO add your handling code here:
        Fhf_JDlgCliente jDlgCliente = new Fhf_JDlgCliente(null, true);
        jDlgCliente.setVisible(true);
    }//GEN-LAST:event_jMnClientesActionPerformed

    private void jMnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnProdutosActionPerformed
        // TODO add your handling code here:
        Fhf_JDlgProduto jDlgProduto = new Fhf_JDlgProduto(null, true);
        jDlgProduto.setVisible(true);
    }//GEN-LAST:event_jMnProdutosActionPerformed

    private void jMnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnVendedorActionPerformed
        // TODO add your handling code here:
        Fhf_JDlgVendedor jDlgVendedor = new Fhf_JDlgVendedor(null, true);
        jDlgVendedor.setVisible(true);
    }//GEN-LAST:event_jMnVendedorActionPerformed

    private void jMnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnVendasActionPerformed
        // TODO add your handling code here:
        Fhf_JDlgVendas jDlgVendas = new Fhf_JDlgVendas(null, true);
        jDlgVendas.setVisible(true);
    }//GEN-LAST:event_jMnVendasActionPerformed

    private void jMnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fhf_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fhf_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fhf_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fhf_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fhf_JFrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnClientes;
    private javax.swing.JMenuItem jMnProdutos;
    private javax.swing.JMenuItem jMnSair;
    private javax.swing.JMenuItem jMnUsuarios;
    private javax.swing.JMenuItem jMnVendas;
    private javax.swing.JMenuItem jMnVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
