/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.FhfClientes;
import bean.FhfProduto;
import bean.FhfVendas;
import bean.FhfVendasproduto;
import bean.FhfVendedor;
import dao.ClientesDAO;
import dao.VendasDAO;
import dao.VendasProdutoDAO;
import dao.VendedorDAO;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tools.Util;

/**
 *
 * @author User
 */
public class Fhf_JDlgVendas extends javax.swing.JDialog {

    FhfControllerVendasProdutos fhfcontrollerVendasProdutos;
    /**
     * Creates new form Fhf_JDlgVendas
     */
    boolean incluir = false;
    boolean pesquisano = false;

    public Fhf_JDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendas");
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(251, 250, 246));
        Util.habilitar(false, jTxtCodigo, jTxtFormaPagamento, jTxtTotal, jCboCliente, jCboVendedor, jFmtData, jBtnConfirmar, jBtnCancelar);

        ClientesDAO clientesDAO = new ClientesDAO();
        List lista = (List) clientesDAO.listAll();
        for (int i = 0; i < lista.size(); i++) {
            jCboCliente.addItem((FhfClientes) lista.get(i));
        }
        VendedorDAO vendedorDAO = new VendedorDAO();
        List lista2 = (List) vendedorDAO.listAll();
        for (int i = 0; i < lista2.size(); i++) {
            jCboVendedor.addItem((FhfVendedor) lista2.get(i));
        }

        fhfcontrollerVendasProdutos = new FhfControllerVendasProdutos();
        fhfcontrollerVendasProdutos.setList(new ArrayList());
        jTable1.setModel(fhfcontrollerVendasProdutos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public FhfVendas viewBean() {
        FhfVendas vendas = new FhfVendas();
        vendas.setFhfIdVendas(Util.strToInt(jTxtCodigo.getText()));
        vendas.setFhfData(Util.strToDate(jFmtData.getText()));
        vendas.setFhfClientes((FhfClientes) jCboCliente.getSelectedItem());
        vendas.setFhfVendedor((FhfVendedor) jCboVendedor.getSelectedItem());
        vendas.setFhfFormaPagamento(jTxtFormaPagamento.getText());
        vendas.setFhfTotal(Util.strToDouble(jTxtTotal.getText()));
        return vendas;
    }

    public void beanView(FhfVendas vendas) {
        jTxtCodigo.setText(Util.intToStr(vendas.getFhfIdVendas()));
        jFmtData.setText(Util.dateToStr(vendas.getFhfData()));
        jCboCliente.setSelectedItem(vendas.getFhfClientes());
        jCboVendedor.setSelectedItem(vendas.getFhfVendedor());
        jTxtFormaPagamento.setText(vendas.getFhfFormaPagamento());
        jTxtTotal.setText(Util.doubleToStr(vendas.getFhfTotal()));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFmtData = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jCboCliente = new javax.swing.JComboBox<FhfClientes>();
        jLabel4 = new javax.swing.JLabel();
        jCboVendedor = new javax.swing.JComboBox<FhfVendedor
        >();
        jLabel5 = new javax.swing.JLabel();
        jTxtFormaPagamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnIncluirProd = new javax.swing.JButton();
        jBtnAlterarProd = new javax.swing.JButton();
        jBtnExcluirProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Número do Pedido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, -1));
        getContentPane().add(jTxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 28, 92, -1));

        jLabel2.setText("Data do Pedido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 6, -1, -1));

        try {
            jFmtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFmtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 28, 99, -1));

        jLabel3.setText("Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 6, -1, -1));

        getContentPane().add(jCboCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 28, 113, -1));

        jLabel4.setText("Vendedor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 6, -1, -1));

        getContentPane().add(jCboVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 28, 113, -1));

        jLabel5.setText("Forma de Pagamento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));
        getContentPane().add(jTxtFormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 122, 30));

        jLabel6.setText("Total");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        jTxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 100, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 670, 280));

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-selecionado-24.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancelar-24.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-24.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, -1));

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-24.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jBtnIncluirComponentHidden(evt);
            }
        });
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-substituir-24.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-remover-23.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        jBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-24.png"))); // NOI18N
        jBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirProdActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIncluirProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 40, -1));

        jBtnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-substituir-24.png"))); // NOI18N
        jBtnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarProdActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAlterarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 40, -1));

        jBtnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-remover-23.png"))); // NOI18N
        jBtnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirProdActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExcluirProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        if (jTxtCodigo.getText().equals("")
                || jFmtData.getText().contains(" ")
                || jTxtFormaPagamento.getText().equals("")
                || jTxtTotal.getText().equals("")) {

            Util.mensagem("Todos os campos devem ser preenchidos corretamente.");
            return;
        }
        VendasDAO vendasDAO = new VendasDAO();
        VendasProdutoDAO vendasProdutoDAO = new VendasProdutoDAO();
        FhfVendas fhfVendas = viewBean();
        if (incluir == true) {
            vendasDAO.insert(viewBean());
            for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                FhfVendasproduto vendasproduto = fhfcontrollerVendasProdutos.getBean(ind);
                vendasproduto.setFhfVendas(fhfVendas);
                vendasProdutoDAO.insert(vendasproduto);
            }
        } else {
            vendasDAO.update(viewBean());
            for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                FhfVendasproduto vendasproduto = fhfcontrollerVendasProdutos.getBean(ind);
                vendasproduto.setFhfVendas(fhfVendas);
                vendasProdutoDAO.update(vendasproduto);

            }
            Util.habilitar(false, jTxtCodigo, jTxtFormaPagamento, jTxtTotal, jCboCliente, jCboVendedor, jFmtData, jBtnConfirmar, jBtnCancelar);
            Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
            Util.limpar(jTxtCodigo, jTxtFormaPagamento, jTxtTotal, jCboCliente, jCboVendedor, jFmtData);
        }
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtCodigo, jTxtFormaPagamento, jTxtTotal, jCboCliente, jCboVendedor, jFmtData, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        Util.limpar(jTxtCodigo, jTxtFormaPagamento, jTxtTotal, jCboCliente, jCboVendedor, jFmtData);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        Fhf_JDlgVendasPesquisar jDlgVendasPesquisar = new Fhf_JDlgVendasPesquisar(null, true);
        jDlgVendasPesquisar.setTelaPai(this);
        jDlgVendasPesquisar.setVisible(true);
        pesquisano = true;

    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jBtnIncluirComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnIncluirComponentHidden

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtCodigo, jTxtFormaPagamento, jTxtTotal, jCboCliente, jCboVendedor, jFmtData, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        Util.limpar(jTxtCodigo, jTxtFormaPagamento, jTxtTotal, jCboCliente, jCboVendedor, jFmtData);
        incluir = true;
        jTxtCodigo.grabFocus();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        if (pesquisano == false) {
            Util.mensagem("Você precisa pesquisar um usuário antes");
        } else {
            Util.habilitar(true, jTxtFormaPagamento, jTxtTotal, jCboCliente, jCboVendedor, jFmtData, jBtnConfirmar, jBtnCancelar);
            Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
            Util.limpar(jTxtCodigo, jTxtFormaPagamento, jTxtTotal, jCboCliente, jCboVendedor, jFmtData);
            incluir = false;
            jFmtData.grabFocus();
        }
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (pesquisano == false) {
            Util.mensagem("Você precisa chamar um usuário antes de excluir");
        } else {
            VendasDAO vendasDAO = new VendasDAO();
            if (Util.perguntar("Você deseja excluir?") == true) {
                vendasDAO.delete(viewBean());
                Util.limpar(jTxtCodigo, jTxtFormaPagamento, jTxtTotal, jCboCliente, jCboVendedor, jFmtData);
            }
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirProdActionPerformed
        // TODO add your handling code here:
        Fhf_JDlgVendasProduto jDlgVendasProduto = new Fhf_JDlgVendasProduto(null, true);
        jDlgVendasProduto.setTelaAnterior(this);
        jDlgVendasProduto.setVisible(true);
    }//GEN-LAST:event_jBtnIncluirProdActionPerformed

    private void jBtnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarProdActionPerformed
        // TODO add your handling code here:
        Fhf_JDlgVendasProduto dlgVendasProduto = new Fhf_JDlgVendasProduto(null, true);
        dlgVendasProduto.setVisible(true);
    }//GEN-LAST:event_jBtnAlterarProdActionPerformed

    private void jBtnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirProdActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Deseja excluir o produto ?") == true) {
            int ind = jTable1.getSelectedRow();
            fhfcontrollerVendasProdutos.removeBean(ind);
        }
    }//GEN-LAST:event_jBtnExcluirProdActionPerformed

    private void jTxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fhf_JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fhf_JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fhf_JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fhf_JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Fhf_JDlgVendas dialog = new Fhf_JDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterarProd;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluirProd;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluirProd;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<FhfClientes> jCboCliente;
    private javax.swing.JComboBox<FhfVendedor> jCboVendedor;
    private javax.swing.JFormattedTextField jFmtData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtFormaPagamento;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
