package bean;
// Generated 07/10/2025 14:56:19 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FhfClientes generated by hbm2java
 */
@Entity
@Table(name="fhf_clientes"
    ,catalog="db_fernando_flores"
)
public class FhfClientes  implements java.io.Serializable {


     private int fhfIdClientes;
     private String fhfNome;
     private String fhfCpf;
     private String fhfSexo;
     private String fhfRg;
     private String fhfEmail;
     private Date fhfDataNascimento;
     private String fhfCep;
     private String fhfEndereco;
     private String fhfBairro;
     private String fhfCidade;
     private String fhfEstado;
     private String fhfCelular;
     private Date fhfDataCadastro;
     private String fhfAtivo;

    public FhfClientes() {
    }

	
    public FhfClientes(String fhfNome, String fhfCpf, String fhfSexo, String fhfRg, String fhfEmail, Date fhfDataNascimento, String fhfCep, String fhfEndereco, String fhfBairro, String fhfCidade, String fhfEstado, String fhfCelular, Date fhfDataCadastro, String fhfAtivo) {
        this.fhfNome = fhfNome;
        this.fhfCpf = fhfCpf;
        this.fhfSexo = fhfSexo;
        this.fhfRg = fhfRg;
        this.fhfEmail = fhfEmail;
        this.fhfDataNascimento = fhfDataNascimento;
        this.fhfCep = fhfCep;
        this.fhfEndereco = fhfEndereco;
        this.fhfBairro = fhfBairro;
        this.fhfCidade = fhfCidade;
        this.fhfEstado = fhfEstado;
        this.fhfCelular = fhfCelular;
        this.fhfDataCadastro = fhfDataCadastro;
        this.fhfAtivo = fhfAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fhf_idClientes", unique=true, nullable=false)
    public int getFhfIdClientes() {
        return this.fhfIdClientes;
    }
    
    public void setFhfIdClientes(int fhfIdClientes) {
        this.fhfIdClientes = fhfIdClientes;
    }

    
    @Column(name="fhf_nome", nullable=false, length=50)
    public String getFhfNome() {
        return this.fhfNome;
    }
    
    public void setFhfNome(String fhfNome) {
        this.fhfNome = fhfNome;
    }

    
    @Column(name="fhf_cpf", nullable=false, length=14)
    public String getFhfCpf() {
        return this.fhfCpf;
    }
    
    public void setFhfCpf(String fhfCpf) {
        this.fhfCpf = fhfCpf;
    }

    
    @Column(name="fhf_sexo", nullable=false, length=1)
    public String getFhfSexo() {
        return this.fhfSexo;
    }
    
    public void setFhfSexo(String fhfSexo) {
        this.fhfSexo = fhfSexo;
    }

    
    @Column(name="fhf_rg", nullable=false, length=10)
    public String getFhfRg() {
        return this.fhfRg;
    }
    
    public void setFhfRg(String fhfRg) {
        this.fhfRg = fhfRg;
    }

    
    @Column(name="fhf_email", nullable=false, length=50)
    public String getFhfEmail() {
        return this.fhfEmail;
    }
    
    public void setFhfEmail(String fhfEmail) {
        this.fhfEmail = fhfEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fhf_dataNascimento", nullable=false, length=10)
    public Date getFhfDataNascimento() {
        return this.fhfDataNascimento;
    }
    
    public void setFhfDataNascimento(Date fhfDataNascimento) {
        this.fhfDataNascimento = fhfDataNascimento;
    }

    
    @Column(name="fhf_cep", nullable=false, length=15)
    public String getFhfCep() {
        return this.fhfCep;
    }
    
    public void setFhfCep(String fhfCep) {
        this.fhfCep = fhfCep;
    }

    
    @Column(name="fhf_endereco", nullable=false, length=50)
    public String getFhfEndereco() {
        return this.fhfEndereco;
    }
    
    public void setFhfEndereco(String fhfEndereco) {
        this.fhfEndereco = fhfEndereco;
    }

    
    @Column(name="fhf_bairro", nullable=false, length=30)
    public String getFhfBairro() {
        return this.fhfBairro;
    }
    
    public void setFhfBairro(String fhfBairro) {
        this.fhfBairro = fhfBairro;
    }

    
    @Column(name="fhf_cidade", nullable=false, length=30)
    public String getFhfCidade() {
        return this.fhfCidade;
    }
    
    public void setFhfCidade(String fhfCidade) {
        this.fhfCidade = fhfCidade;
    }

    
    @Column(name="fhf_estado", nullable=false, length=2)
    public String getFhfEstado() {
        return this.fhfEstado;
    }
    
    public void setFhfEstado(String fhfEstado) {
        this.fhfEstado = fhfEstado;
    }

    
    @Column(name="fhf_celular", nullable=false, length=13)
    public String getFhfCelular() {
        return this.fhfCelular;
    }
    
    public void setFhfCelular(String fhfCelular) {
        this.fhfCelular = fhfCelular;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fhf_dataCadastro", nullable=false, length=10)
    public Date getFhfDataCadastro() {
        return this.fhfDataCadastro;
    }
    
    public void setFhfDataCadastro(Date fhfDataCadastro) {
        this.fhfDataCadastro = fhfDataCadastro;
    }

    
    @Column(name="fhf_ativo", nullable=false, length=1)
    public String getFhfAtivo() {
        return this.fhfAtivo;
    }
    
    public void setFhfAtivo(String fhfAtivo) {
        this.fhfAtivo = fhfAtivo;
    }

}


