package bean;
// Generated 07/10/2025 14:56:19 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FhfProduto generated by hbm2java
 */
@Entity
@Table(name="fhf_produto"
    ,catalog="db_fernando_flores"
)
public class FhfProduto  implements java.io.Serializable {


     private int fhfIdProduto;
     private String fhfNome;
     private String fhfDescricao;
     private double fhfPreco;
     private int fhfQuantidade;
     private String fhfTipo;
     private Date fhfDataAdicao;

    public FhfProduto() {
    }

	
    public FhfProduto(String fhfNome, String fhfDescricao, double fhfPreco, int fhfQuantidade, String fhfTipo, Date fhfDataAdicao) {
        this.fhfNome = fhfNome;
        this.fhfDescricao = fhfDescricao;
        this.fhfPreco = fhfPreco;
        this.fhfQuantidade = fhfQuantidade;
        this.fhfTipo = fhfTipo;
        this.fhfDataAdicao = fhfDataAdicao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fhf_idProduto", unique=true, nullable=false)
    public int getFhfIdProduto() {
        return this.fhfIdProduto;
    }
    
    public void setFhfIdProduto(int fhfIdProduto) {
        this.fhfIdProduto = fhfIdProduto;
    }

    
    @Column(name="fhf_nome", nullable=false, length=50)
    public String getFhfNome() {
        return this.fhfNome;
    }
    
    public void setFhfNome(String fhfNome) {
        this.fhfNome = fhfNome;
    }

    
    @Column(name="fhf_descricao", nullable=false, length=200)
    public String getFhfDescricao() {
        return this.fhfDescricao;
    }
    
    public void setFhfDescricao(String fhfDescricao) {
        this.fhfDescricao = fhfDescricao;
    }

    
    @Column(name="fhf_preco", nullable=false, precision=10)
    public double getFhfPreco() {
        return this.fhfPreco;
    }
    
    public void setFhfPreco(double fhfPreco) {
        this.fhfPreco = fhfPreco;
    }

    
    @Column(name="fhf_quantidade", nullable=false)
    public int getFhfQuantidade() {
        return this.fhfQuantidade;
    }
    
    public void setFhfQuantidade(int fhfQuantidade) {
        this.fhfQuantidade = fhfQuantidade;
    }

    
    @Column(name="fhf_tipo", nullable=false, length=20)
    public String getFhfTipo() {
        return this.fhfTipo;
    }
    
    public void setFhfTipo(String fhfTipo) {
        this.fhfTipo = fhfTipo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fhf_dataAdicao", nullable=false, length=10)
    public Date getFhfDataAdicao() {
        return this.fhfDataAdicao;
    }
    
    public void setFhfDataAdicao(Date fhfDataAdicao) {
        this.fhfDataAdicao = fhfDataAdicao;
    }

}


