package bean;
// Generated 07/10/2025 14:56:19 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FhfUsuarios generated by hbm2java
 */
@Entity
@Table(name="fhf_usuarios"
    ,catalog="db_fernando_flores"
)
public class FhfUsuarios  implements java.io.Serializable {


     private int fhfIdUsuarios;
     private String fhfNome;
     private String fhfApelido;
     private String fhfCpf;
     private Date fhfDataNascimento;
     private String fhfSenha;
     private int fhfNivel;
     private String fhfAtivo;

    public FhfUsuarios() {
    }

	
    public FhfUsuarios(String fhfNome, String fhfApelido, String fhfCpf, Date fhfDataNascimento, String fhfSenha, int fhfNivel) {
        this.fhfNome = fhfNome;
        this.fhfApelido = fhfApelido;
        this.fhfCpf = fhfCpf;
        this.fhfDataNascimento = fhfDataNascimento;
        this.fhfSenha = fhfSenha;
        this.fhfNivel = fhfNivel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fhf_idUsuarios", unique=true, nullable=false)
    public Integer getFhfIdUsuarios() {
        return this.fhfIdUsuarios;
    }
    
    public void setFhfIdUsuarios(Integer fhfIdUsuarios) {
        this.fhfIdUsuarios = fhfIdUsuarios;
    }

    
    @Column(name="fhf_nome", nullable=false, length=50)
    public String getFhfNome() {
        return this.fhfNome;
    }
    
    public void setFhfNome(String fhfNome) {
        this.fhfNome = fhfNome;
    }

    
    @Column(name="fhf_apelido", nullable=false, length=25)
    public String getFhfApelido() {
        return this.fhfApelido;
    }
    
    public void setFhfApelido(String fhfApelido) {
        this.fhfApelido = fhfApelido;
    }

    
    @Column(name="fhf_cpf", nullable=false, length=14)
    public String getFhfCpf() {
        return this.fhfCpf;
    }
    
    public void setFhfCpf(String fhfCpf) {
        this.fhfCpf = fhfCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fhf_dataNascimento", nullable=false, length=10)
    public Date getFhfDataNascimento() {
        return this.fhfDataNascimento;
    }
    
    public void setFhfDataNascimento(Date fhfDataNascimento) {
        this.fhfDataNascimento = fhfDataNascimento;
    }

    
    @Column(name="fhf_senha", nullable=false)
    public String getFhfSenha() {
        return this.fhfSenha;
    }
    
    public void setFhfSenha(String fhfSenha) {
        this.fhfSenha = fhfSenha;
    }

    
    @Column(name="fhf_nivel", nullable=false)
    public int getFhfNivel() {
        return this.fhfNivel;
    }
    
    public void setFhfNivel(int fhfNivel) {
        this.fhfNivel = fhfNivel;
    }

    
    @Column(name="fhf_ativo", length=1)
    public String getFhfAtivo() {
        return this.fhfAtivo;
    }
    
    public void setFhfAtivo(String fhfAtivo) {
        this.fhfAtivo = fhfAtivo;
    }




}


