package bean;
// Generated 07/10/2025 14:56:19 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FhfVendas generated by hbm2java
 */
@Entity
@Table(name="fhf_vendas"
    ,catalog="db_fernando_flores"
)
public class FhfVendas implements java.io.Serializable {


     private int fhfIdVendas;
     private FhfClientes fhfClientes;
     private FhfVendedor fhfVendedor;
     private Date fhfData;
     private String fhfFormaPagamento;
     private double fhfTotal;

    public FhfVendas() {
    }

	
    public FhfVendas(FhfClientes fhfClientes, FhfVendedor fhfVendedor, Date fhfData, String fhfFormaPagamento, double fhfTotal) {
       this.fhfClientes = fhfClientes;
       this.fhfVendedor = fhfVendedor;
       this.fhfData = fhfData;
       this.fhfFormaPagamento = fhfFormaPagamento;
       this.fhfTotal = fhfTotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fhf_idVendas", unique=true, nullable=false)
    public int getFhfIdVendas() {
        return this.fhfIdVendas;
    }
    
    public void setFhfIdVendas(int fhfIdVendas) {
        this.fhfIdVendas = fhfIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fhf_fkClientes")
    public FhfClientes getFhfClientes() {
        return this.fhfClientes;
    }
    
    public void setFhfClientes(FhfClientes fhfClientes) {
        this.fhfClientes = fhfClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fhf_fkVendedor")
    public FhfVendedor getFhfVendedor() {
        return this.fhfVendedor;
    }
    
    public void setFhfVendedor(FhfVendedor fhfVendedor) {
        this.fhfVendedor = fhfVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fhf_data", nullable=false, length=10)
    public Date getFhfData() {
        return this.fhfData;
    }
    
    public void setFhfData(Date fhfData) {
        this.fhfData = fhfData;
    }

    
    @Column(name="fhf_formaPagamento", length=20)
    public String getFhfFormaPagamento() {
        return this.fhfFormaPagamento;
    }
    
    public void setFhfFormaPagamento(String fhfFormaPagamento) {
        this.fhfFormaPagamento = fhfFormaPagamento;
    }

    
    @Column(name="fhf_total", precision=10)
    public double getFhfTotal() {
        return this.fhfTotal;
    }
    
    public void setFhfTotal(double fhfTotal) {
        this.fhfTotal = fhfTotal;
    }
}


