package bean;
// Generated 07/10/2025 14:56:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FhfVendasproduto generated by hbm2java
 */
@Entity
@Table(name="fhf_vendasproduto"
    ,catalog="db_fernando_flores"
)
public class FhfVendasproduto  implements java.io.Serializable {


     private String fhfIdVendaproduto;
     private FhfProduto fhfProduto;
     private FhfVendas fhfVendas;
     private int fhfQuantidade;
     private double fhfPrecoUnitario;
     private double fhfTotal;

    public FhfVendasproduto() {
    }

	
    public FhfVendasproduto(String fhfIdVendaproduto) {
        this.fhfIdVendaproduto = fhfIdVendaproduto;
    }
    public FhfVendasproduto(String fhfIdVendaproduto, FhfProduto fhfProduto, FhfVendas fhfVendas, int fhfQuantidade, double fhfPrecoUnitario, double fhfTotal) {
       this.fhfIdVendaproduto = fhfIdVendaproduto;
       this.fhfProduto = fhfProduto;
       this.fhfVendas = fhfVendas;
       this.fhfQuantidade = fhfQuantidade;
       this.fhfPrecoUnitario = fhfPrecoUnitario;
       this.fhfTotal = fhfTotal;
    }
   
     @Id 

    
    @Column(name="fhf_idVendaproduto", unique=true, nullable=false, length=45)
    public String getFhfIdVendaproduto() {
        return this.fhfIdVendaproduto;
    }
    
    public void setFhfIdVendaproduto(String fhfIdVendaproduto) {
        this.fhfIdVendaproduto = fhfIdVendaproduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fhf_fkidProduto")
    public FhfProduto getFhfProduto() {
        return this.fhfProduto;
    }
    
    public void setFhfProduto(FhfProduto fhfProduto) {
        this.fhfProduto = fhfProduto;
    }
    
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fhf_fkidVendas")
    public FhfVendas getFhfVendas() {
        return this.fhfVendas;
    }
    
    public void setFhfVendas(FhfVendas fhfVendas) {
        this.fhfProduto = fhfProduto;
    }
    
    @Column(name="fhf_quantidade")
    public int getFhfQuantidade() {
        return this.fhfQuantidade;
    }
    
    public void setFhfQuantidade(int fhfQuantidade) {
        this.fhfQuantidade = fhfQuantidade;
    }

    
    @Column(name="fhf_precoUnitario", precision=10)
    public double getFhfPrecoUnitario() {
        return this.fhfPrecoUnitario;
    }
    
    public void setFhfPrecoUnitario(double fhfPrecoUnitario) {
        this.fhfPrecoUnitario = fhfPrecoUnitario;
    }
    
    @Column(name="fhf_total")
    public double getFhfTotal() {
        return this.fhfTotal;
    }
    
    public void setFhfTotal(double fhfTotal) {
        this.fhfTotal = fhfTotal;
    }


}


