package bean;
// Generated 07/10/2025 14:56:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FhfVendedor generated by hbm2java
 */
@Entity
@Table(name="fhf_vendedor"
    ,catalog="db_fernando_flores"
)
public class FhfVendedor implements java.io.Serializable {


     private int fhfIdVendedor;
     private String fhfNome;
     private String fhfCpf;
     private String fhfTelefone;
     private int fhfTurno;
     private double fhfSalario;
     private String fhfEndereco;

    public FhfVendedor() {
    }

	
    public FhfVendedor(int fhfIdVendedor, String fhfNome, String fhfCpf, String fhfTelefone, int fhfTurno, double fhfSalario, String fhfEndereco) {
        this.fhfIdVendedor = fhfIdVendedor;
        this.fhfNome = fhfNome;
        this.fhfCpf = fhfCpf;
        this.fhfTelefone = fhfTelefone;
        this.fhfTurno = fhfTurno;
        this.fhfSalario = fhfSalario;
        this.fhfEndereco = fhfEndereco;
    }
    
    @Column(name="fhf_idVendedor", unique=true, nullable=false)
     @Id @GeneratedValue(strategy=IDENTITY)
    public int getFhfIdVendedor() {
        return this.fhfIdVendedor;
    }
    
    public void setFhfIdVendedor(int fhfIdVendedor) {
        this.fhfIdVendedor = fhfIdVendedor;
    }

    
    @Column(name="fhf_nome", nullable=false, length=50)
    public String getFhfNome() {
        return this.fhfNome;
    }
    
    public void setFhfNome(String fhfNome) {
        this.fhfNome = fhfNome;
    }

    
    @Column(name="fhf_cpf", nullable=false, length=14)
    public String getFhfCpf() {
        return this.fhfCpf;
    }
    
    public void setFhfCpf(String fhfCpf) {
        this.fhfCpf = fhfCpf;
    }

    
    @Column(name="fhf_telefone", nullable=false, length=13)
    public String getFhfTelefone() {
        return this.fhfTelefone;
    }
    
    public void setFhfTelefone(String fhfTelefone) {
        this.fhfTelefone = fhfTelefone;
    }

    
    @Column(name="fhf_turno", nullable=false, length=12)
    public int getFhfTurno() {
        return this.fhfTurno;
    }
    
    public void setFhfTurno(int fhfTurno) {
        this.fhfTurno = fhfTurno;
    }

    
    @Column(name="fhf_salario", nullable=false, precision=10)
    public double getFhfSalario() {
        return this.fhfSalario;
    }
    
    public void setFhfSalario(double fhfSalario) {
        this.fhfSalario = fhfSalario;
    }

    
    @Column(name="fhf_endereco", nullable=false, length=50)
    public String getFhfEndereco() {
        return this.fhfEndereco;
    }
    
    public void setFhfEndereco(String fhfEndereco) {
        this.fhfEndereco = fhfEndereco;
    }
    
     @Override
    public String toString() {
        return this.fhfNome;
    }
    @Override
    public boolean equals(Object object) {
        if (object instanceof FhfVendedor) {
            if (this.getFhfIdVendedor()== ((FhfVendedor) object).getFhfIdVendedor()) {
                return true;
            }
        }
        return false;
    }
}


